### ISSUE TITLE
(Question) Bias T support 

### ISSUE THREAD

**Issue by alphafox02** [softsyst/RSP3_tcp#1]
Would this version of rsp_tcp happen to support turning on/off the internal bias t on the rsp1a? It seems like this version has had more recent development then the original rsp_tcp. 

Edit: Have you built Linux binaries?

**Comment by softsyst** [comment]
RSP3_tcp (and its predecessor RSP2_tcp) are not "a version of rsp_tcp". They are an independent development which are in no way influenced or inspired by rsp_tcp, with the RSP2_tcp having been realized perhaps even earlier (not sure about this though). 
They are intended to cooperate with the [QIRX ](https://qirx.softsyst.com)SDR. The interface is open and can be inspected here in the sources.

The "2" in RSP2_tcp was motivated by the (now out dated) sdrplay driver version 2.x, the "3" in RSP3_tcp means it supports sdrplay's driver V3.x.

Yes, it supports the BiasT for all supported RSP hardware, i.e. RSP1A, RSP2, RSPduo and the RSPdx.
There is no Linux build yet, due to other priorities.

**Comment by alphafox02** [comment]
Thank you for the explanation and that’s great to hear it’s completely independent/different then rsp_tcp. QIRX led me here, I was thinking of trying it with wine, but then thought rsp3_tcp native in Linux would be a great pair for it and other applications. I’m using the v3 api, figured that’s what the 3 meant. If you get around to a Linux build or if I figure out how to build your source for Linux I’d happily test.

**Comment by softsyst** [comment]
The Linux port is since long on my list, especially after the introduction of the native Linux console version of qirx. If you want to try it yourself, there should be no peculiarities which could prevent it. There are already some of the usual #ifdefs due to the Win socket library, but otherwise all should be posix compatible. Of course, one has to test it, and the sdrplay driver has to be installed.

**Comment by alphafox02** [comment]
Sorry last question and I’ll close this ticket out and work on it. I assume the Linux 3.07 api is okay? That’s the highest api I can find for Linux or at least what it shows on the sdrplay site. I’ll check what the actually version comes up as once instslled. 

Edit: I see the 3.07 documents.
